spring:
  profiles:
    group:
      release:
        - redis-release
        - jwt-release
        - oauth-release
        - file-release

      release2:
        - redis-release
        - jwt-release
        - oauth-release
        - file-release
      develop:
        - redis-dev
        - jwt-dev
        - oauth-dev
        - file-release

    active: develop