kakao:
  client_id: 9338dac6db9d9162c95333adbcb97200
  redirect: "https://nohoo.site/api/oauth/kakao/callback"
  url:
    token:
      host: "kauth.kakao.com"
      path: "/oauth/token"
    profile:
      host: "kapi.kakao.com"
      path: "/v2/user/me"