kakao:
  client_id: ad1df559dc905b03ec9d59ad4afbe212
  redirect: "https://nohoo.site/api/oauth/kakao/callback"
  url:
    token:
      host: "kauth.kakao.com"
      path: "/oauth/token"
    profile:
      host: "kapi.kakao.com"
      path: "/v2/user/me"