spring:
  profiles:
    group:
      release:
        - redis-release
        - jwt-release
        - oauth-release
      develop:
        - redis-dev
        - jwt-dev
        - oauth-dev

    active: develop