spring:
  profiles:
    group:
      release:
        - redis-release
        - jwt-release
        - kakao-release
      develop:
        - redis-dev
        - jwt-dev
        - kakao-dev

    active: develop