spring:
  config:
    activate:
      on-profile: "release2"

  initDb:
    enable: false

  datasource:
    url: jdbc:mariadb://nohoo.site:3306/nova?characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: zhelddldksehlaus!!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  com.sehbeomschool.nova: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8081

security:
  require-ssl: true


